### ISSUE TITLE
Please add a 'stop running' button aside the 'run' button.

### ISSUE THREAD

**Issue by LYMI2771** [roslynpad/roslynpad#417] opened 2021-12-27 07:43 UTC
Hello there,

I need a stop button to kill the program process.

I think maybe someone else need this too.

now the only way stop the infinite looping program is taskkill.

Thanks.

**Comment by aelij** [comment] 2021-12-27 09:26
Duplicate of #415

**Closed by aelij** 2021-12-27 09:26 UTC
