### ISSUE TITLE
Start the program and then flash back

### ISSUE THREAD

**Issue by HoboCY** [roslynpad/roslynpad#460] opened 2023-03-07 08:35 UTC
**When I ran dotnet RoslynPad.dll, the application window came out and immediately closed with an error:**
Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at RoslynPad.UI.OpenDocumentViewModel.set_Platform(ExecutionPlatform value) in C:\src\github\aelij\RoslynPad\src\RoslynPad.Common.UI\ViewModels\OpenDocumentViewModel.cs:line 437
   at RoslynPad.UI.OpenDocumentViewModel.Initialize(DocumentId documentId, Action`1 onError, Func`1 getSelection, IDisposable viewDisposable) in C:\src\github\aelij\RoslynPad\src\RoslynPad.Common.UI\ViewModels\OpenDocumentViewModel.cs:line 596
   at RoslynPad.DocumentView.OnDataContextChanged(Object sender, EventArgs args) in C:\src\github\aelij\RoslynPad\src\RoslynPad.Avalonia\DocumentView.axaml.cs:line 61
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.JobWithArg.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 241
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4502
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at RoslynPad.Program.Main(String[] args) in C:\src\github\aelij\RoslynPad\src\RoslynPad.Avalonia\Program.cs:line 13
zsh: abort      dotnet RoslynPad.dll

- RoslynPad Version: 17
- OS: MacOS Ventura 13.2.1
- CPU: Apple M1 Pro

**Comment by aelij** [comment] 2023-05-01 20:11
Duplicate of #459. Can you please also reply to my questions there?

**Closed by aelij** 2023-05-01 20:11 UTC

**Comment by HoboCY** [comment] 2023-05-12 01:08
> Duplicate of #459. Can you please also reply to my questions there?
> 
> 459号的复印件，请你也回答我的问题好吗？

OK

**Comment by adrianoc** [comment] 2023-08-03 13:17
@aelij 

> Duplicate of #459. Can you please also reply to my questions there?

are you sure these are duplicates ?

The call stacks are different.

Regardless, I am trying to run RoslynPad (release 18) on Ubuntu  22.04 and I am getting the same behavior as described by @HoboCY 

Btw, result of `dotnet --info` :

.NET SDK:
 Version:   7.0.109
 Commit:    3e9283a8e9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.109/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.109 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.9 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by aelij** [comment] 2023-08-04 20:51
@adrianoc can you please share the stack trace?

**Comment by adrianoc** [comment] 2023-08-05 04:08
@aelij of course, sorry, I should have included it in the previous msg.


```
dotnet /tmp/RoslynPadAvalonia/RoslynPad.dll

Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at RoslynPad.UI.OpenDocumentViewModel.set_Platform(ExecutionPlatform value) in D:\src\gh\aelij\roslynpad\src\RoslynPad.Common.UI\ViewModels\OpenDocumentViewModel.cs:line 453
   at RoslynPad.UI.OpenDocumentViewModel.Initialize(DocumentId documentId, Action`1 onError, Func`1 getSelection, IDisposable viewDisposable) in D:\src\gh\aelij\roslynpad\src\RoslynPad.Common.UI\ViewModels\OpenDocumentViewModel.cs:line 615
   at RoslynPad.DocumentView.OnDataContextChanged(Object sender, EventArgs args) in D:\src\gh\aelij\roslynpad\src\RoslynPad.Avalonia\DocumentView.axaml.cs:line 60
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 392
   at Avalonia.Threading.DispatcherOperation.Execute() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 262
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job) in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 122
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 153
   at Avalonia.Threading.Dispatcher.Signaled() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 133
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 119
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 196
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl) in /_/src/Avalonia.Base/Threading/DispatcherFrame.cs:line 117
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 53
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 80
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 127
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 220
   at RoslynPad.Program.Main(String[] args) in D:\src\gh\aelij\roslynpad\src\RoslynPad.Avalonia\Program.cs:line 13
```
